from .preprocessor import Preprocessor
from .extract import Extract
from .createfolderstructure import CreateFolderStructure
from .renamenotebooks import RenameNotebooks
from .addextrafiles import AddExtraFiles
from .deletetempfolders import DeleteTempFolders
from .restructuresubmission import RestructureSubmission
from .extractfeedback import ExtractFeedback
from .extractassignmentinfo import ExtractAssignmentInfo
from .movetosubmitted import MoveToSubmitted
from .copyfeedback import CopyFeedback
from .zipfeedback import ZipFeedback