from .preprocessor import Preprocessor
from .addextrafiles import AddExtraFiles
from .copyfeedback import CopyFeedback
from .copygroupfeedback import CopyGroupFeedback
from .createfolderstructure import CreateFolderStructure
from .deletetempfolders import DeleteTempFolders
from .extract import Extract
from .extractassignmentinfo import ExtractAssignmentInfo
from .extractfeedback import ExtractFeedback
from .extractsinglesubmission import ExtractSingleSubmission
from .groupsubmissions import GroupSubmissions
from .movetosubmitted import MoveToSubmitted
from .renamenotebooks import RenameNotebooks
from .renamesubmission import RenameSubmission
from .restructuresubmission import RestructureSubmission
from .zipfeedback import ZipFeedback